name: Matka Scraper

on:
  schedule:
    - cron: '0 * * * 1-6'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Run scraper
      run: python csvFiles/main.py

    - name: Push changes
      run: |
       git config --global user.name "github-actions"
       git config --global user.email "github-actions@github.com"
       git add .
       git diff --cached --quiet || git commit -m "Update CSV results"
       git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/LINEADDA/Digit_backend.git HEAD:main
